[package]
name = "dataflow"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]

[dependencies]
wiggles_value = { path = "../wiggles_value" }
ordermap = "*"
log = "*"
serde = "*"
serde_derive = "*"