[package]
name = "websocket_server"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]

[dependencies]
websocket = "*"
hyper = "0.10.12"
local-ip = "*"
futures = "*"
rand = "*"