[package]
name = "wiggles_value"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]

[dependencies]
serde_derive = "*"
try_from = "*"

[dependencies.serde]
version = "*"
features = ["rc"]