[package]
name = "core_console_test"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]

[dependencies]
console_server = { path = "../console_server" }
serde = "*"
serde_derive = "*"
log = "*"
simple_logger = "*"