[package]
name = "fixture-patch"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]

[dependencies]
wiggles_value = { path = "../wiggles-value" }
rust_dmx = { git = "https://github.com/generalelectrix/rust-dmx" }
